### ISSUE TITLE
Store Model in Component: overflow evaluating the requirement

### ISSUE THREAD

**Issue by FilePhil** [janhohenheim/share_wgpu_between_bevy_and_burn#1]
Hey,

I wanted to try to use bevy and burn for a small reinforcement learning project and saw this Repo on Discord.

I facing the Issue that my example code will show this error message:

> error[E0275]: overflow evaluating the requirement `naga::_::InternalBitFlags: Sync`
   --> src/main.rs:24:8
    |
24  | struct Model{
    |        ^^^^^
    |

The Example works fine with Burn 0.16.
Do you have an Idea how i could fix this?

Thank you,
Phil

### Used cargo.toml
```toml
[dependencies]
bevy = { version = "0.16.0-rc.2"}

[dependencies.burn]
version = "0.17.0"
git = "https://github.com/tracel-ai/burn"
rev = "975db6a4c133836d27dbfe0123ed7ffab37233bb"
features = ["wgpu", "train", "autodiff"]
```

### Example main.rs:
```rust
use std::sync::{Arc, Mutex};

use burn::nn::{Linear, LinearConfig};

use burn::tensor::Tensor;

use burn::tensor::activation::relu;

use burn::backend::{Autodiff, Wgpu};

use burn::prelude::Module;

use bevy::prelude::*;

type MyBackend = Wgpu<f32>;
type MyAutodiff =Autodiff<MyBackend>;

#[derive(Component)]
struct ModelComponent{
    model: Arc<Mutex<Model>>,
}

#[derive(Module,Debug,Clone)]
struct Model{
    linear_0: Linear<MyAutodiff>,
    linear_1: Linear<MyAutodiff>,
    linear_2: Linear<MyAutodiff>,
}

impl Model{
    fn forward(&self, input: Tensor::<MyAutodiff, 2>) ->  Tensor::<MyAutodiff, 2>{

        let output = relu(self.linear_0.forward(input));
        let output = relu(self.linear_1.forward(output));
        let output = relu(self.linear_2.forward(output));
        return output;
    }
}

const INPUT_SIZE:usize = 4;
const HIDDEN_SIZE:usize = 4096;
const OUTPUT_SIZE:usize = 4;

fn setup(mut commands: Commands){  

    let entity = commands.spawn_empty().id();

    let my_net = Model{
        linear_0: LinearConfig::new(INPUT_SIZE, HIDDEN_SIZE).init(&Default::default()), 
        linear_1: LinearConfig::new(HIDDEN_SIZE, HIDDEN_SIZE).init(&Default::default()),
        linear_2: LinearConfig::new(HIDDEN_SIZE, OUTPUT_SIZE).init(&Default::default()),
    };

    let model_component = ModelComponent{
        model: Arc::new(Mutex::from(my_net)),
    };

    commands.entity(entity).insert(model_component);

}

fn use_model(
    query: Query<&mut ModelComponent>,
    ){ 
        
    for container in query.iter() {
        let frame_no: f32 = frame.0 as f32;
        let foats = [[frame_no*0.1, frame_no*0.2,frame_no*0.3,frame_no*0.4];2];

        let net = container.model.lock().unwrap();
        
        let tensor = Tensor::<MyAutodiff, 2>::from_floats(foats, &Default::default());
        let output = net.forward(tensor);

        println!("{}" output);
    }
}


fn main() {
    let mut app = App::new();
    app.add_plugins(MinimalPlugins);

    app.add_systems(Startup, setup);
    app.add_systems(Update,use_model);

    app.run();
}

```

**Comment by janhohenheim** [comment]
Yep, there's a WGPU upgrade commit on Bevy's side that should work :) I can try finding it later
